/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.HeadlessException;
import java.sql.Connection;

import java.util.Date;
import java.util.*;
import java.text.DateFormat;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JLabel;
import java.util.Random;
/**
 *
 * @author Amritha
 */
public class booking extends javax.swing.JFrame {
    
   public Connection conn; 
   ResultSet rs;
   PreparedStatement psss;
    /**
     * Creates new form register
     * @throws java.sql.SQLException
     */
    
     public booking() throws SQLException {
        initComponents();
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            // The credentials for the mysql account will differ
            this.conn =(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/hms","root","amri");
            
        }
        catch(ClassNotFoundException e){System.out.println(e);}
    }
     public booking(String hid) throws SQLException {
        initComponents();
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            // The credentials for the mysql account will differ
            this.conn =(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/hms","root","amri");
            
        }
        catch(ClassNotFoundException e){System.out.println(e);}
        hotelid.setText(hid);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        email = new java.awt.TextField();
        label1 = new java.awt.Label();
        label3 = new java.awt.Label();
        label5 = new java.awt.Label();
        fname = new java.awt.TextField();
        aadhar = new java.awt.TextField();
        hotelid = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();
        bookid = new javax.swing.JLabel();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        chout = new com.toedter.calendar.JDateChooser();
        chin = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        label2 = new java.awt.Label();
        label6 = new java.awt.Label();
        roomtype = new javax.swing.JComboBox<>();
        noofrooms = new java.awt.TextField();
        label7 = new java.awt.Label();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 168, 190, -1));

        label1.setBackground(new java.awt.Color(51, 51, 51));
        label1.setForeground(new java.awt.Color(240, 240, 240));
        label1.setText("Hotel ID");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 30, -1, -1));

        label3.setBackground(new java.awt.Color(51, 51, 51));
        label3.setForeground(new java.awt.Color(240, 240, 240));
        label3.setText("Aadhar(or Passport) number");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 128, -1, -1));

        label5.setBackground(new java.awt.Color(51, 51, 51));
        label5.setForeground(new java.awt.Color(240, 240, 240));
        label5.setText("Email ID");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 168, -1, -1));
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 89, 190, -1));
        getContentPane().add(aadhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 128, 190, -1));
        getContentPane().add(hotelid, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 30, 70, -1));

        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Booking ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 63, 95, -1));

        bookid.setBackground(new java.awt.Color(51, 51, 51));
        bookid.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(bookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 63, 150, 16));

        label8.setBackground(new java.awt.Color(51, 51, 51));
        label8.setForeground(new java.awt.Color(240, 240, 240));
        label8.setText("Check-in");
        getContentPane().add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 250, -1, -1));

        label9.setBackground(new java.awt.Color(51, 51, 51));
        label9.setForeground(new java.awt.Color(240, 240, 240));
        label9.setText("Check-out");
        getContentPane().add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 248, -1, -1));
        getContentPane().add(chout, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 248, -1, -1));
        getContentPane().add(chin, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 248, -1, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(240, 240, 240));

        jButton3.setText("Proceed to payment");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        label2.setBackground(new java.awt.Color(51, 51, 51));
        label2.setForeground(new java.awt.Color(240, 240, 240));
        label2.setText("First Name");

        label6.setBackground(new java.awt.Color(51, 51, 51));
        label6.setForeground(new java.awt.Color(240, 240, 240));
        label6.setText("Room type");

        roomtype.setBackground(new java.awt.Color(51, 51, 51));
        roomtype.setForeground(new java.awt.Color(0, 102, 255));
        roomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single suite", "Honeymoon suite", "Triple suite", "Family suite" }));
        roomtype.setOpaque(false);
        roomtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomtypeActionPerformed(evt);
            }
        });

        noofrooms.setBackground(new java.awt.Color(51, 0, 51));

        label7.setBackground(new java.awt.Color(51, 51, 51));
        label7.setForeground(new java.awt.Color(240, 240, 240));
        label7.setText("No. of Rooms");

        jButton1.setText("BACK TO HOTELS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("TOTAL:");

        total.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        total.setForeground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(126, 126, 126)
                                .addComponent(noofrooms, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(143, 143, 143)
                                .addComponent(roomtype, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(53, 53, 53)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noofrooms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(roomtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(51, 51, 51))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roomtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomtypeActionPerformed
        // TODO add your handling code here:
         Random ran = new Random();
            int num;
            num = ran.nextInt(1000);
            String n;
            n = Integer.toString(num);
            bookid.setText(n);
            
            try {
            
            String hid=hotelid.getText();
            int nr=Integer.parseInt(noofrooms.getText());
            try {
             
                 psss = conn.prepareStatement("select * from roomtype where hotelid=?");
                 psss.setString(1,hid);
                 rs=psss.executeQuery();
                        if(rs.next()) {
                            String s;
                            s = (String)roomtype.getSelectedItem();
                            if("Single suite".equals(s)) {
                                int price = rs.getInt("singleroom");
                                int tota=price*nr;
                                String tot;
                                tot = Integer.toString(tota);
                                total.setText(tot); 
                            }
                            if("Honeymoon suite".equals(s)) {
                                int price = rs.getInt("honeymoon");
                                String tot;
                                tot = Integer.toString(price*nr);
                                total.setText(tot); 
                            }
                            if("Triple suite".equals(s)) {
                                int price = rs.getInt("triple");
                                int tota=price*nr;
                                String tot;
                                tot = Integer.toString(tota);
                                total.setText(tot); 
                            }
                            if("Family suite".equals(s)) {
                                int price = rs.getInt("family");
                                int tota=price*nr;
                                String tot;
                                tot = Integer.toString(tota);
                                total.setText(tot); 
                            }
                        }
                    
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            }
            catch (HeadlessException | NumberFormatException e) { JOptionPane.showMessageDialog(null, e); }
    }//GEN-LAST:event_roomtypeActionPerformed

    
    

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();  
            hotels hot = null;
            hot = new hotels();
            hot.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try {
            
            String sql;
            sql = "insert into booking values(?,?,?,?,?,?,?,?,?)";
            PreparedStatement ps = null;
            
                ps = conn.prepareStatement(sql);
            
            String n=bookid.getText();
            ps.setString(2,n);
            ps.setString(1, hotelid.getText());
            ps.setString(3, fname.getText());
            ps.setString(4, aadhar.getText());
            ps.setString(5, email.getText());
            Date date1 = chin.getDate();
            Date date2 = chout.getDate();
            String strDate1 = DateFormat.getDateInstance().format(date1);
            String strDate2 = DateFormat.getDateInstance().format(date2);
            ps.setString(6, strDate1);
            ps.setString(7, strDate2);
            String ss=(String)roomtype.getSelectedItem();
            ps.setString(8,ss);
            ps.setString(9, noofrooms.getText());
           
            ps.execute();
            String msg1 = bookid.getText();
            String msg2 = fname.getText();
            String msg3 = email.getText();
            String msg4 = ss;
            String msg5 = noofrooms.getText();
            
            this.dispose();
            new Payment(msg1,msg2,msg3,msg4,msg5).setVisible(true);
        
        } catch (SQLException ex) {
            Logger.getLogger(booking.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new booking().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(booking.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField aadhar;
    private javax.swing.JLabel bookid;
    private com.toedter.calendar.JDateChooser chin;
    private com.toedter.calendar.JDateChooser chout;
    private java.awt.TextField email;
    private java.awt.TextField fname;
    private java.awt.TextField hotelid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.TextField noofrooms;
    private javax.swing.JComboBox<String> roomtype;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
