/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Amritha
 */
public class bookingt extends javax.swing.JFrame {

    public Connection conn;
    PreparedStatement psss, ps2;
    ResultSet rs;

    /**
     * Creates new form bookingt
     */
    public bookingt() throws SQLException {
        initComponents();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            // The credentials for the mysql account will differ
            this.conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hms", "root", "amri");

        } catch (ClassNotFoundException e) {
            System.out.println(e);
        }
    }

    public bookingt(String user, String tid) throws SQLException {
        initComponents();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            // The credentials for the mysql account will differ
            this.conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hms", "root", "amri");

        } catch (ClassNotFoundException e) {
            System.out.println(e);
        }
        tourid.setText(tid);
        try {
            String sql2 = "Select fname,adhar from register where email=?";

            try {
                ps2 = conn.prepareStatement(sql2);
            } catch (SQLException ex) {
                Logger.getLogger(user_roomhistory.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                ps2.setString(1, user);
            } catch (SQLException ex) {
                Logger.getLogger(user_roomhistory.class.getName()).log(Level.SEVERE, null, ex);
            }
            ResultSet rs = ps2.executeQuery();
            while (rs.next()) {
                name.setText(rs.getString("fname"));
                aadhar.setText(rs.getString("adhar"));
                emailid.setText(user);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tourpack = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        tourid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bookid = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        aadhar = new javax.swing.JTextField();
        emailid = new javax.swing.JTextField();
        noofp = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 10, 59, 25);

        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Booking ID");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 80, 130, 16);

        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 110, 140, 16);

        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Aadhar");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(130, 150, 130, 16);

        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Email");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 190, 120, 16);

        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("No. of Persons");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(130, 280, 120, 16);

        tourpack.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5D/4N", "9D/8N" }));
        tourpack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tourpackMouseClicked(evt);
            }
        });
        tourpack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tourpackActionPerformed(evt);
            }
        });
        jPanel1.add(tourpack);
        tourpack.setBounds(270, 320, 130, 30);

        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Tour Package");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(130, 320, 120, 16);

        tourid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                touridActionPerformed(evt);
            }
        });
        jPanel1.add(tourid);
        tourid.setBounds(490, 20, 80, 22);

        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Tour ID:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(420, 20, 48, 16);

        bookid.setBackground(new java.awt.Color(51, 51, 51));
        bookid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bookid.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(bookid);
        bookid.setBounds(330, 70, 170, 30);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name);
        name.setBounds(330, 110, 120, 22);
        jPanel1.add(aadhar);
        aadhar.setBounds(330, 150, 120, 22);
        jPanel1.add(emailid);
        emailid.setBounds(330, 190, 180, 30);

        noofp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noofpActionPerformed(evt);
            }
        });
        jPanel1.add(noofp);
        noofp.setBounds(280, 272, 110, 30);

        jButton2.setText("Proceed to payment");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(400, 390, 180, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("TOTAL:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(360, 360, 70, 17);

        total.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        total.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(total);
        total.setBounds(430, 350, 140, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void touridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_touridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_touridActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void noofpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noofpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noofpActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        try {

            String sql;
            sql = "insert into bookingt values(?,?,?,?,?,?,?)";
            PreparedStatement ps = null;

            ps = conn.prepareStatement(sql);

            String n = bookid.getText();
            ps.setString(2, n);
            ps.setString(1, tourid.getText());
            ps.setString(3, name.getText());
            ps.setString(4, aadhar.getText());
            ps.setString(5, emailid.getText());
            int ss = Integer.parseInt(noofp.getText());
            ps.setInt(6, ss);
            String sp = (String) tourpack.getSelectedItem();
            ps.setString(7, sp);

            ps.execute();
            String msg1 = bookid.getText();
            String msg2 = name.getText();
            String msg3 = emailid.getText();
            int msg4 = ss;
            String msg5 = sp;

            this.dispose();
            new Payment(msg1, msg2, msg3, msg4, msg5).setVisible(true);

        } catch (SQLException ex) {
            Logger.getLogger(booking.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tourpackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tourpackActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_tourpackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        tours tor = null;
        tor = new tours();
        tor.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tourpackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tourpackMouseClicked
        // TODO add your handling code here:

        Random ran = new Random();
        int num;
        num = ran.nextInt(1000);
        String n;
        n = Integer.toString(num);
        bookid.setText(n);

        try {

            String tid = tourid.getText();
            int nr = Integer.parseInt(noofp.getText());
            try {
                psss = conn.prepareStatement("select * from tourpack where tourid=?");
                psss.setString(1, tid);
                rs = psss.executeQuery();
                if (rs.next()) {
                    String s;
                    s = (String) tourpack.getSelectedItem();
                    if ("5D/4N".equals(s)) {
                        int price = rs.getInt("5d4n");
                        int tota = price * nr;
                        String tot;
                        tot = Integer.toString(tota);
                        total.setText(tot);
                    }
                    if ("9D/8N".equals(s)) {
                        int price = rs.getInt("9d8n");
                        int tota = price * nr;
                        String tot;
                        tot = Integer.toString(tota);
                        total.setText(tot);
                    }
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tourpackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookingt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookingt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookingt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookingt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new bookingt().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(bookingt.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aadhar;
    private javax.swing.JLabel bookid;
    private javax.swing.JTextField emailid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField noofp;
    private javax.swing.JLabel total;
    private javax.swing.JTextField tourid;
    private javax.swing.JComboBox<String> tourpack;
    // End of variables declaration//GEN-END:variables
}
