/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Amritha
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
        
    }
    public Payment(String para1,String para2,String para3,String para4,String para5){
         initComponents();
         bookid.setText(para1);
         fname.setText(para2);
         email.setText(para3);
         roomtype.setText(para4);
         noofrooms.setText(para5);
         
         
     }
    public Payment(String para1,String para2,String para3,int para4,String para5){
         initComponents();
         bookid.setText(para1);
         fname.setText(para2);
         email.setText(para3);
         String p=Integer.toString(para4);
         roomtype.setText(p);
         noofrooms.setText(para5);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        name = new java.awt.TextField();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        bookid = new java.awt.Label();
        fname = new java.awt.Label();
        email = new java.awt.Label();
        roomtype = new java.awt.Label();
        noofrooms = new java.awt.Label();
        jButton1 = new javax.swing.JButton();
        card = new java.awt.TextField();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        cvv = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setBackground(new java.awt.Color(51, 51, 51));
        label1.setForeground(new java.awt.Color(240, 240, 240));
        label1.setText("Card Payment");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        label2.setBackground(new java.awt.Color(51, 51, 51));
        label2.setForeground(new java.awt.Color(240, 240, 240));
        label2.setText("Name on card");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 240, -1, -1));

        label3.setBackground(new java.awt.Color(51, 51, 51));
        label3.setForeground(new java.awt.Color(240, 240, 240));
        label3.setText("Card Number");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 270, -1, -1));

        label4.setBackground(new java.awt.Color(51, 51, 51));
        label4.setForeground(new java.awt.Color(240, 240, 240));
        label4.setText("CVV");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 300, -1, -1));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 240, 191, -1));

        label8.setBackground(new java.awt.Color(51, 51, 51));
        label8.setForeground(new java.awt.Color(240, 240, 240));
        label8.setText("BOOKINGID");
        getContentPane().add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 45, -1, -1));

        label9.setBackground(new java.awt.Color(51, 51, 51));
        label9.setForeground(new java.awt.Color(240, 240, 240));
        label9.setText("NAME");
        getContentPane().add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 75, -1, -1));

        label10.setBackground(new java.awt.Color(51, 51, 51));
        label10.setForeground(new java.awt.Color(240, 240, 240));
        label10.setText("EMAIL");
        getContentPane().add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 105, -1, -1));

        label11.setBackground(new java.awt.Color(51, 51, 51));
        label11.setForeground(new java.awt.Color(240, 240, 240));
        label11.setText("TYPE");
        getContentPane().add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 135, -1, -1));

        label12.setBackground(new java.awt.Color(51, 51, 51));
        label12.setForeground(new java.awt.Color(240, 240, 240));
        label12.setText("NO OF ROOMS / NO OF PERSONS");
        getContentPane().add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 165, -1, -1));

        bookid.setBackground(new java.awt.Color(51, 51, 51));
        bookid.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(bookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 45, 117, -1));

        fname.setBackground(new java.awt.Color(51, 51, 51));
        fname.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 75, 117, -1));

        email.setBackground(new java.awt.Color(51, 51, 51));
        email.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 105, 117, -1));

        roomtype.setBackground(new java.awt.Color(51, 51, 51));
        roomtype.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(roomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 135, 117, -1));

        noofrooms.setBackground(new java.awt.Color(51, 51, 51));
        noofrooms.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(noofrooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 165, 117, -1));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        card.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardActionPerformed(evt);
            }
        });
        getContentPane().add(card, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 270, 191, -1));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jButton2.setText("CONFIRM BOOKING");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cvv.setForeground(new java.awt.Color(240, 240, 240));
        cvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(270, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cvv, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(305, Short.MAX_VALUE)
                .addComponent(cvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();  
           booking bok = null;
        try {
            bok = new booking();
        } catch (SQLException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        }
       
            bok.setVisible(true); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         if (name.getText().equals("") || card.getText().length() != 16 || cvv.getText().length() != 3) {
                    JOptionPane.showMessageDialog(null, "INVALID PAYMENT INFO");

                    cvv.setText("");
                    card.setText("");
//            this.dispose();  
//            Payment pay = null;
//            pay = new Payment();
//            pay.setVisible(true); 
                   
                } 
      
            else {
             
            String msg1 = bookid.getText();
            String msg2 = fname.getText();
            String msg3 = email.getText();
            String msg4 = roomtype.getText();
            String msg5 = noofrooms.getText();
            
            this.dispose();
            new receipt(msg1,msg2,msg3,msg4,msg5).setVisible(true);
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cardActionPerformed

    private void cvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label bookid;
    private java.awt.TextField card;
    private java.awt.TextField cvv;
    private java.awt.Label email;
    private java.awt.Label fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.TextField name;
    private java.awt.Label noofrooms;
    private java.awt.Label roomtype;
    // End of variables declaration//GEN-END:variables
}
